apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: atri-server
spec:
  description: "ATRI VPS 后端（自带网页控制台 /admin；打开域名自动进入控制台）"
  tags:
    - atri
    - ai
    - chat
    - admin
  variables:
    - key: DOMAIN
      type: DOMAIN
      name: 访问域名
      description: Zeabur 生成的 *.zeabur.app 子域名
    - key: POSTGRES_PASSWORD
      type: STRING
      name: 数据库密码
      description: PostgreSQL 密码（请用强密码）
    - key: APP_TOKEN
      type: STRING
      name: APP_TOKEN
      description: 客户端调用本服务的鉴权 token（请用强密码）
    - key: ADMIN_API_KEY
      type: STRING
      name: ADMIN_API_KEY
      description: 管理后台登录密钥（请用强密码）
    - key: ADMIN_CONFIG_ENCRYPTION_KEY
      type: STRING
      name: ADMIN_CONFIG_ENCRYPTION_KEY
      description: 用于加密保存上游密钥（推荐 openssl rand -base64 32）
  readme: |
    # ATRI Server（Zeabur 一键部署）

    部署完成后直接访问你的域名，会自动跳到 `/admin` 进入控制台。

    - 管理后台登录：用你填写的 `ADMIN_API_KEY`
    - 上游（OpenAI/Anthropic/Gemini）与 Embeddings：可以部署后在后台里配置（保存即生效）
    - 上游 Base URL：只需要填到 `/v1` 之前，后台会自动补全版本路径

  services:
    - name: db
      template: PREBUILT
      spec:
        id: db
        name: db
        source:
          image: "pgvector/pgvector:pg16"
        ports:
          - id: tcp
            port: 5432
            type: TCP
        env:
          POSTGRES_USER:
            default: "atri"
          POSTGRES_PASSWORD:
            default: ${POSTGRES_PASSWORD}
          POSTGRES_DB:
            default: "atri"
        volumes:
          - id: db-data
            dir: /var/lib/postgresql/data

    - name: api
      template: PREBUILT
      spec:
        id: api
        name: api
        source:
          image: ghcr.io/mikuscat/atri-server
        ports:
          - id: web
            port: 3111
            type: HTTP
        env:
          HOST:
            default: "0.0.0.0"
          PORT:
            default: "3111"
          MEDIA_ROOT:
            default: "/data/media"
          DATABASE_URL:
            default: postgres://atri:${POSTGRES_PASSWORD}@db.zeabur.internal:5432/atri
          APP_TOKEN:
            default: ${APP_TOKEN}
          ADMIN_API_KEY:
            default: ${ADMIN_API_KEY}
          ADMIN_CONFIG_ENCRYPTION_KEY:
            default: ${ADMIN_CONFIG_ENCRYPTION_KEY}
          ADMIN_PUBLIC:
            default: "1"
          PUBLIC_BASE_URL:
            default: https://${DOMAIN}
          ADMIN_ALLOWED_ORIGINS:
            default: https://${DOMAIN}
        volumes:
          - id: api-data
            dir: /data
